project_name: shine
version: 2
builds:
  - main: ./cmd/shine
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: rewdy
    name: shine