name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       goos: [linux, windows, darwin]
  #       goarch: [amd64, arm64]

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.19

  #     - name: Build binary
  #       run: |
  #         mkdir -p dist
  #         GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/shine-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/shine

  #     - name: Upload Release Asset
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         token: ${{ secrets.TOKEN }}
  #         files: dist/*
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}