name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build binary
        run: |
          mkdir -p dist
          make build-releases

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: shine-binaries
          path: dist/